name: Notify Slack on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: actions/github-script@v6
        with:
          script: |
            const webhookUrl = process.env.SLACK_WEBHOOK_URL;
            const issue = context.payload.issue;

            const message = {
              text: `A new issue has been created:\n\n*Title:* ${issue.title}\n*Description:* ${issue.body || "No description"}\n*Created by:* ${issue.user.login}\n*URL:* ${issue.html_url}`
            };

            const response = await fetch(webhookUrl, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(message)
            });

            if (!response.ok) {
              throw new Error(`Slack notification failed: ${response.statusText}`);
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
