name: Notify Slack on Push

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: actions/github-script@v6
        with:
          script: |
            const webhookUrl = process.env.SLACK_WEBHOOK_URL;
            const commit = context.payload.head_commit;

            const message = {
              text: `A new push has been made:\n\n*Branch:* ${commit.ref}\n*Commit Message:* ${commit.message}\n*Author:* ${commit.author.name}\n*URL:* ${commit.url}`
            };

            const response = await fetch(webhookUrl, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(message)
            });

            if (!response.ok) {
              throw new Error(`Slack notification failed: ${response.statusText}`);
            }
    env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
